#!/bin/bash

CERTBOT_LOC=/etc/letsencrypt/live/airpacfire.eecs.wsu.edu

cd ../

# Kill gunicorn server instance
sudo pkill -f gunicorn

# Restart server with logs
sudo gunicorn -w3 --bind 0.0.0.0:80 --log-level debug --log-file master_log AIRPACT_Fire.wsgi:application 
#sudo gunicorn -w3 --bind 0.0.0.0:80 --log-level debug --log-file master_log --certfile $CERTBOT_LOC/cert.pem --keyfile $CERTBOT_LOC/privkey.pem AIRPACT_Fire.wsgi:application 
