#!/bin/bash

# NOTE: A cron job has been setup to run this script every hour.

# Kill gunicorn server instance
sudo pkill -f gunicorn

# Pull down most recent changes
git pull

# Restart server
sudo gunicorn --bind localhost:8080 AIRPACT_Fire.wsgi:application
